### ISSUE TITLE
Algorithm iterating just once

### ISSUE THREAD

**Issue by Oyatsumi** [fengChenHPC/kmeans_cuda#1]
cudaMemset(d_delta, 0, sizeof(int));

then d_delta is not passed to any kernel

then theres the while logic:    while (delta > threshold);

and the algorithm iterates just once.

Could you fix that if possible?
Thank you so much.

**Comment by fengChenHPC** [comment]
thanks for using this code.

the code is right, we use d_delta to store error, and copy back to delta

**Comment by Oyatsumi** [comment]
Thank you instead,

Did you run the same code and it iterated more than one time in the while loop?

Could you please perform this test?

My point is:
If nothing is done with d_delta and its content (0) is passed to the host variable delta, then delta is always zero and the while loop doesnt loop at all. How is the threshold variable supposed to work?

**Comment by monchin** [comment]
The same problem
